/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AlertRule {
  'id' : bigint,
  'active' : boolean,
  'frequency' : string,
  'condition' : string,
}
export interface Asset {
  'id' : bigint,
  'ticker' : string,
  'averageEntryPrice' : [] | [bigint],
  'name' : string,
  'timeHorizon' : string,
  'allocation' : bigint,
}
export interface DailyBrief {
  'keyDrivers' : Array<string>,
  'watchNext' : Array<string>,
  'date' : bigint,
  'volatilityScore' : bigint,
  'summary' : string,
  'liquidityScore' : bigint,
  'signalNoiseScore' : bigint,
  'riskScore' : Array<RiskCatalyst>,
  'bullishScore' : bigint,
}
export interface PortfolioSnapshot {
  'date' : bigint,
  'assets' : Array<Asset>,
  'opportunities' : Array<string>,
  'allocation' : bigint,
  'healthScore' : bigint,
  'risks' : Array<string>,
}
export interface Profile {
  'email' : string,
  'topics' : Array<string>,
  'timeZone' : string,
}
export interface ResearchItem {
  'id' : bigint,
  'justification' : string,
  'topic' : string,
  'catalysts' : Array<string>,
  'saved' : boolean,
  'score' : bigint,
  'summary' : string,
  'keyPoints' : Array<string>,
  'risks' : Array<string>,
}
export interface RiskCatalyst {
  'id' : bigint,
  'impact' : string,
  'description' : string,
}
export interface _SERVICE {
  'addAsset' : ActorMethod<
    [string, string, bigint, string, [] | [bigint]],
    undefined
  >,
  'createAlertRule' : ActorMethod<[string, string], bigint>,
  'createDailyBrief' : ActorMethod<
    [
      string,
      Array<[bigint, string, string]>,
      bigint,
      bigint,
      bigint,
      bigint,
      Array<string>,
      Array<string>,
    ],
    bigint
  >,
  'createPortfolioSnapshot' : ActorMethod<
    [bigint, Array<string>, Array<string>],
    bigint
  >,
  'createResearchItem' : ActorMethod<
    [
      string,
      string,
      Array<string>,
      Array<string>,
      Array<string>,
      bigint,
      string,
    ],
    bigint
  >,
  'getAlertRule' : ActorMethod<[bigint], AlertRule>,
  'getDailyBrief' : ActorMethod<[bigint], DailyBrief>,
  'getPortfolioSnapshot' : ActorMethod<[bigint], PortfolioSnapshot>,
  'getProfile' : ActorMethod<[string], [] | [Profile]>,
  'getResearchItem' : ActorMethod<[bigint], ResearchItem>,
  'listAlertRules' : ActorMethod<[], Array<[bigint, AlertRule]>>,
  'listDailyBriefs' : ActorMethod<[], Array<[bigint, DailyBrief]>>,
  'listPortfolioSnapshots' : ActorMethod<
    [],
    Array<[bigint, PortfolioSnapshot]>
  >,
  'listResearchItems' : ActorMethod<[], Array<[bigint, ResearchItem]>>,
  'saveResearchItem' : ActorMethod<[bigint], undefined>,
  'toggleAlertRule' : ActorMethod<[bigint], undefined>,
  'updateProfile' : ActorMethod<[string, string, Array<string>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];