/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AlertRule = IDL.Record({
  'id' : IDL.Nat,
  'active' : IDL.Bool,
  'frequency' : IDL.Text,
  'condition' : IDL.Text,
});
export const RiskCatalyst = IDL.Record({
  'id' : IDL.Nat,
  'impact' : IDL.Text,
  'description' : IDL.Text,
});
export const DailyBrief = IDL.Record({
  'keyDrivers' : IDL.Vec(IDL.Text),
  'watchNext' : IDL.Vec(IDL.Text),
  'date' : IDL.Int,
  'volatilityScore' : IDL.Nat,
  'summary' : IDL.Text,
  'liquidityScore' : IDL.Nat,
  'signalNoiseScore' : IDL.Nat,
  'riskScore' : IDL.Vec(RiskCatalyst),
  'bullishScore' : IDL.Nat,
});
export const Asset = IDL.Record({
  'id' : IDL.Nat,
  'ticker' : IDL.Text,
  'averageEntryPrice' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'timeHorizon' : IDL.Text,
  'allocation' : IDL.Nat,
});
export const PortfolioSnapshot = IDL.Record({
  'date' : IDL.Int,
  'assets' : IDL.Vec(Asset),
  'opportunities' : IDL.Vec(IDL.Text),
  'allocation' : IDL.Nat,
  'healthScore' : IDL.Nat,
  'risks' : IDL.Vec(IDL.Text),
});
export const Profile = IDL.Record({
  'email' : IDL.Text,
  'topics' : IDL.Vec(IDL.Text),
  'timeZone' : IDL.Text,
});
export const ResearchItem = IDL.Record({
  'id' : IDL.Nat,
  'justification' : IDL.Text,
  'topic' : IDL.Text,
  'catalysts' : IDL.Vec(IDL.Text),
  'saved' : IDL.Bool,
  'score' : IDL.Nat,
  'summary' : IDL.Text,
  'keyPoints' : IDL.Vec(IDL.Text),
  'risks' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'addAsset' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'createAlertRule' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'createDailyBrief' : IDL.Func(
      [
        IDL.Text,
        IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text, IDL.Text)),
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'createPortfolioSnapshot' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'createResearchItem' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Nat,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'getAlertRule' : IDL.Func([IDL.Nat], [AlertRule], ['query']),
  'getDailyBrief' : IDL.Func([IDL.Nat], [DailyBrief], ['query']),
  'getPortfolioSnapshot' : IDL.Func([IDL.Nat], [PortfolioSnapshot], ['query']),
  'getProfile' : IDL.Func([IDL.Text], [IDL.Opt(Profile)], ['query']),
  'getResearchItem' : IDL.Func([IDL.Nat], [ResearchItem], ['query']),
  'listAlertRules' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, AlertRule))],
      ['query'],
    ),
  'listDailyBriefs' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, DailyBrief))],
      ['query'],
    ),
  'listPortfolioSnapshots' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, PortfolioSnapshot))],
      ['query'],
    ),
  'listResearchItems' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, ResearchItem))],
      ['query'],
    ),
  'saveResearchItem' : IDL.Func([IDL.Nat], [], []),
  'toggleAlertRule' : IDL.Func([IDL.Nat], [], []),
  'updateProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(IDL.Text)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AlertRule = IDL.Record({
    'id' : IDL.Nat,
    'active' : IDL.Bool,
    'frequency' : IDL.Text,
    'condition' : IDL.Text,
  });
  const RiskCatalyst = IDL.Record({
    'id' : IDL.Nat,
    'impact' : IDL.Text,
    'description' : IDL.Text,
  });
  const DailyBrief = IDL.Record({
    'keyDrivers' : IDL.Vec(IDL.Text),
    'watchNext' : IDL.Vec(IDL.Text),
    'date' : IDL.Int,
    'volatilityScore' : IDL.Nat,
    'summary' : IDL.Text,
    'liquidityScore' : IDL.Nat,
    'signalNoiseScore' : IDL.Nat,
    'riskScore' : IDL.Vec(RiskCatalyst),
    'bullishScore' : IDL.Nat,
  });
  const Asset = IDL.Record({
    'id' : IDL.Nat,
    'ticker' : IDL.Text,
    'averageEntryPrice' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'timeHorizon' : IDL.Text,
    'allocation' : IDL.Nat,
  });
  const PortfolioSnapshot = IDL.Record({
    'date' : IDL.Int,
    'assets' : IDL.Vec(Asset),
    'opportunities' : IDL.Vec(IDL.Text),
    'allocation' : IDL.Nat,
    'healthScore' : IDL.Nat,
    'risks' : IDL.Vec(IDL.Text),
  });
  const Profile = IDL.Record({
    'email' : IDL.Text,
    'topics' : IDL.Vec(IDL.Text),
    'timeZone' : IDL.Text,
  });
  const ResearchItem = IDL.Record({
    'id' : IDL.Nat,
    'justification' : IDL.Text,
    'topic' : IDL.Text,
    'catalysts' : IDL.Vec(IDL.Text),
    'saved' : IDL.Bool,
    'score' : IDL.Nat,
    'summary' : IDL.Text,
    'keyPoints' : IDL.Vec(IDL.Text),
    'risks' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'addAsset' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'createAlertRule' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'createDailyBrief' : IDL.Func(
        [
          IDL.Text,
          IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text, IDL.Text)),
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'createPortfolioSnapshot' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'createResearchItem' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Nat,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'getAlertRule' : IDL.Func([IDL.Nat], [AlertRule], ['query']),
    'getDailyBrief' : IDL.Func([IDL.Nat], [DailyBrief], ['query']),
    'getPortfolioSnapshot' : IDL.Func(
        [IDL.Nat],
        [PortfolioSnapshot],
        ['query'],
      ),
    'getProfile' : IDL.Func([IDL.Text], [IDL.Opt(Profile)], ['query']),
    'getResearchItem' : IDL.Func([IDL.Nat], [ResearchItem], ['query']),
    'listAlertRules' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, AlertRule))],
        ['query'],
      ),
    'listDailyBriefs' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, DailyBrief))],
        ['query'],
      ),
    'listPortfolioSnapshots' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, PortfolioSnapshot))],
        ['query'],
      ),
    'listResearchItems' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, ResearchItem))],
        ['query'],
      ),
    'saveResearchItem' : IDL.Func([IDL.Nat], [], []),
    'toggleAlertRule' : IDL.Func([IDL.Nat], [], []),
    'updateProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(IDL.Text)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };