/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AlertRule = IDL.Record({
  'id' : IDL.Nat,
  'active' : IDL.Bool,
  'frequency' : IDL.Text,
  'condition' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'email' : IDL.Text,
  'topics' : IDL.Vec(IDL.Text),
  'isPro' : IDL.Bool,
  'timeZone' : IDL.Text,
});
export const RiskCatalyst = IDL.Record({
  'id' : IDL.Nat,
  'impact' : IDL.Text,
  'description' : IDL.Text,
});
export const DailyBrief = IDL.Record({
  'keyDrivers' : IDL.Vec(IDL.Text),
  'watchNext' : IDL.Vec(IDL.Text),
  'date' : IDL.Int,
  'volatilityScore' : IDL.Nat,
  'summary' : IDL.Text,
  'liquidityScore' : IDL.Nat,
  'signalNoiseScore' : IDL.Nat,
  'riskScore' : IDL.Vec(RiskCatalyst),
  'bullishScore' : IDL.Nat,
});
export const MarketPulseUpdate = IDL.Record({
  'id' : IDL.Nat,
  'updateText' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Asset = IDL.Record({
  'id' : IDL.Nat,
  'ticker' : IDL.Text,
  'averageEntryPrice' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'timeHorizon' : IDL.Text,
  'allocation' : IDL.Nat,
});
export const PortfolioSnapshot = IDL.Record({
  'date' : IDL.Int,
  'assets' : IDL.Vec(Asset),
  'opportunities' : IDL.Vec(IDL.Text),
  'allocation' : IDL.Nat,
  'healthScore' : IDL.Nat,
  'risks' : IDL.Vec(IDL.Text),
});
export const ResearchItem = IDL.Record({
  'id' : IDL.Nat,
  'justification' : IDL.Text,
  'topic' : IDL.Text,
  'catalysts' : IDL.Vec(IDL.Text),
  'saved' : IDL.Bool,
  'score' : IDL.Nat,
  'summary' : IDL.Text,
  'keyPoints' : IDL.Vec(IDL.Text),
  'risks' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAsset' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAlertRule' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'createDailyBrief' : IDL.Func(
      [
        IDL.Text,
        IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text, IDL.Text)),
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'createMarketPulseUpdate' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'createPortfolioSnapshot' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'createResearchItem' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Nat,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'getAlertRule' : IDL.Func([IDL.Nat], [AlertRule], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyBrief' : IDL.Func([IDL.Nat], [IDL.Opt(DailyBrief)], ['query']),
  'getMarketPulseUpdate' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(MarketPulseUpdate)],
      ['query'],
    ),
  'getPortfolioSnapshot' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(PortfolioSnapshot)],
      ['query'],
    ),
  'getProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
  'getResearchItem' : IDL.Func([IDL.Nat], [ResearchItem], ['query']),
  'getTodaysBrief' : IDL.Func([], [IDL.Opt(DailyBrief)], ['query']),
  'getTodaysMarketPulseUpdate' : IDL.Func(
      [],
      [IDL.Opt(MarketPulseUpdate)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isProUser' : IDL.Func([], [IDL.Bool], ['query']),
  'listAlertRules' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, AlertRule))],
      ['query'],
    ),
  'listDailyBriefs' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, DailyBrief))],
      ['query'],
    ),
  'listMarketPulseUpdates' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, MarketPulseUpdate))],
      ['query'],
    ),
  'listPortfolioSnapshots' : IDL.Func(
      [],
      [IDL.Vec(PortfolioSnapshot)],
      ['query'],
    ),
  'listResearchItems' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, ResearchItem))],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveResearchItem' : IDL.Func([IDL.Nat], [], []),
  'setProStatus' : IDL.Func([IDL.Bool], [], []),
  'toggleAlertRule' : IDL.Func([IDL.Nat], [], []),
  'updateProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(IDL.Text)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AlertRule = IDL.Record({
    'id' : IDL.Nat,
    'active' : IDL.Bool,
    'frequency' : IDL.Text,
    'condition' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'email' : IDL.Text,
    'topics' : IDL.Vec(IDL.Text),
    'isPro' : IDL.Bool,
    'timeZone' : IDL.Text,
  });
  const RiskCatalyst = IDL.Record({
    'id' : IDL.Nat,
    'impact' : IDL.Text,
    'description' : IDL.Text,
  });
  const DailyBrief = IDL.Record({
    'keyDrivers' : IDL.Vec(IDL.Text),
    'watchNext' : IDL.Vec(IDL.Text),
    'date' : IDL.Int,
    'volatilityScore' : IDL.Nat,
    'summary' : IDL.Text,
    'liquidityScore' : IDL.Nat,
    'signalNoiseScore' : IDL.Nat,
    'riskScore' : IDL.Vec(RiskCatalyst),
    'bullishScore' : IDL.Nat,
  });
  const MarketPulseUpdate = IDL.Record({
    'id' : IDL.Nat,
    'updateText' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Asset = IDL.Record({
    'id' : IDL.Nat,
    'ticker' : IDL.Text,
    'averageEntryPrice' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'timeHorizon' : IDL.Text,
    'allocation' : IDL.Nat,
  });
  const PortfolioSnapshot = IDL.Record({
    'date' : IDL.Int,
    'assets' : IDL.Vec(Asset),
    'opportunities' : IDL.Vec(IDL.Text),
    'allocation' : IDL.Nat,
    'healthScore' : IDL.Nat,
    'risks' : IDL.Vec(IDL.Text),
  });
  const ResearchItem = IDL.Record({
    'id' : IDL.Nat,
    'justification' : IDL.Text,
    'topic' : IDL.Text,
    'catalysts' : IDL.Vec(IDL.Text),
    'saved' : IDL.Bool,
    'score' : IDL.Nat,
    'summary' : IDL.Text,
    'keyPoints' : IDL.Vec(IDL.Text),
    'risks' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAsset' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAlertRule' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'createDailyBrief' : IDL.Func(
        [
          IDL.Text,
          IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text, IDL.Text)),
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'createMarketPulseUpdate' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'createPortfolioSnapshot' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'createResearchItem' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Nat,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'getAlertRule' : IDL.Func([IDL.Nat], [AlertRule], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyBrief' : IDL.Func([IDL.Nat], [IDL.Opt(DailyBrief)], ['query']),
    'getMarketPulseUpdate' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(MarketPulseUpdate)],
        ['query'],
      ),
    'getPortfolioSnapshot' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(PortfolioSnapshot)],
        ['query'],
      ),
    'getProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
    'getResearchItem' : IDL.Func([IDL.Nat], [ResearchItem], ['query']),
    'getTodaysBrief' : IDL.Func([], [IDL.Opt(DailyBrief)], ['query']),
    'getTodaysMarketPulseUpdate' : IDL.Func(
        [],
        [IDL.Opt(MarketPulseUpdate)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isProUser' : IDL.Func([], [IDL.Bool], ['query']),
    'listAlertRules' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, AlertRule))],
        ['query'],
      ),
    'listDailyBriefs' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, DailyBrief))],
        ['query'],
      ),
    'listMarketPulseUpdates' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, MarketPulseUpdate))],
        ['query'],
      ),
    'listPortfolioSnapshots' : IDL.Func(
        [],
        [IDL.Vec(PortfolioSnapshot)],
        ['query'],
      ),
    'listResearchItems' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, ResearchItem))],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveResearchItem' : IDL.Func([IDL.Nat], [], []),
    'setProStatus' : IDL.Func([IDL.Bool], [], []),
    'toggleAlertRule' : IDL.Func([IDL.Nat], [], []),
    'updateProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(IDL.Text)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };