/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DailyBrief {
    keyDrivers: Array<string>;
    watchNext: Array<string>;
    date: bigint;
    volatilityScore: bigint;
    summary: string;
    liquidityScore: bigint;
    signalNoiseScore: bigint;
    riskScore: Array<RiskCatalyst>;
    bullishScore: bigint;
}
export interface RiskCatalyst {
    id: bigint;
    impact: string;
    description: string;
}
export interface PortfolioSnapshot {
    date: bigint;
    assets: Array<Asset>;
    opportunities: Array<string>;
    allocation: bigint;
    healthScore: bigint;
    risks: Array<string>;
}
export interface ResearchItem {
    id: bigint;
    justification: string;
    topic: string;
    catalysts: Array<string>;
    saved: boolean;
    score: bigint;
    summary: string;
    keyPoints: Array<string>;
    risks: Array<string>;
}
export interface Asset {
    id: bigint;
    ticker: string;
    averageEntryPrice?: bigint;
    name: string;
    timeHorizon: string;
    allocation: bigint;
}
export interface AlertRule {
    id: bigint;
    active: boolean;
    frequency: string;
    condition: string;
}
export interface UserProfile {
    email: string;
    topics: Array<string>;
    isPro: boolean;
    timeZone: string;
}
export interface MarketPulseUpdate {
    id: bigint;
    updateText: string;
    timestamp: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAsset(name: string, ticker: string, allocation: bigint, timeHorizon: string, averageEntryPrice: bigint | null): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAlertRule(condition: string, frequency: string): Promise<bigint>;
    createDailyBrief(summary: string, riskCatalysts: Array<[bigint, string, string]>, bullishScore: bigint, volatilityScore: bigint, liquidityScore: bigint, signalNoiseScore: bigint, keyDrivers: Array<string>, watchNext: Array<string>): Promise<bigint>;
    createMarketPulseUpdate(updateText: string, previousUpdateText: string): Promise<bigint>;
    createPortfolioSnapshot(healthScore: bigint, risks: Array<string>, opportunities: Array<string>): Promise<bigint>;
    createResearchItem(topic: string, summary: string, keyPoints: Array<string>, risks: Array<string>, catalysts: Array<string>, score: bigint, justification: string): Promise<bigint>;
    getAlertRule(id: bigint): Promise<AlertRule>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDailyBrief(id: bigint): Promise<DailyBrief | null>;
    getMarketPulseUpdate(id: bigint): Promise<MarketPulseUpdate | null>;
    getPortfolioSnapshot(id: bigint): Promise<PortfolioSnapshot | null>;
    getProfile(email: string): Promise<UserProfile | null>;
    getResearchItem(id: bigint): Promise<ResearchItem>;
    getTodaysBrief(): Promise<DailyBrief | null>;
    getTodaysMarketPulseUpdate(): Promise<MarketPulseUpdate | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isProUser(): Promise<boolean>;
    listAlertRules(): Promise<Array<[bigint, AlertRule]>>;
    listDailyBriefs(): Promise<Array<[bigint, DailyBrief]>>;
    listMarketPulseUpdates(): Promise<Array<[bigint, MarketPulseUpdate]>>;
    listPortfolioSnapshots(): Promise<Array<PortfolioSnapshot>>;
    listResearchItems(): Promise<Array<[bigint, ResearchItem]>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveResearchItem(id: bigint): Promise<void>;
    setProStatus(isPro: boolean): Promise<void>;
    toggleAlertRule(id: bigint): Promise<void>;
    updateProfile(email: string, timeZone: string, topics: Array<string>): Promise<void>;
}
import type { Asset as _Asset, DailyBrief as _DailyBrief, MarketPulseUpdate as _MarketPulseUpdate, PortfolioSnapshot as _PortfolioSnapshot, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAsset(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAsset(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAsset(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAlertRule(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createAlertRule(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAlertRule(arg0, arg1);
            return result;
        }
    }
    async createDailyBrief(arg0: string, arg1: Array<[bigint, string, string]>, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: Array<string>, arg7: Array<string>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createDailyBrief(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDailyBrief(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async createMarketPulseUpdate(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createMarketPulseUpdate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMarketPulseUpdate(arg0, arg1);
            return result;
        }
    }
    async createPortfolioSnapshot(arg0: bigint, arg1: Array<string>, arg2: Array<string>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPortfolioSnapshot(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPortfolioSnapshot(arg0, arg1, arg2);
            return result;
        }
    }
    async createResearchItem(arg0: string, arg1: string, arg2: Array<string>, arg3: Array<string>, arg4: Array<string>, arg5: bigint, arg6: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createResearchItem(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createResearchItem(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async getAlertRule(arg0: bigint): Promise<AlertRule> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlertRule(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlertRule(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyBrief(arg0: bigint): Promise<DailyBrief | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyBrief(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyBrief(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMarketPulseUpdate(arg0: bigint): Promise<MarketPulseUpdate | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketPulseUpdate(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketPulseUpdate(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPortfolioSnapshot(arg0: bigint): Promise<PortfolioSnapshot | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioSnapshot(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioSnapshot(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(arg0: string): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResearchItem(arg0: bigint): Promise<ResearchItem> {
        if (this.processError) {
            try {
                const result = await this.actor.getResearchItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResearchItem(arg0);
            return result;
        }
    }
    async getTodaysBrief(): Promise<DailyBrief | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodaysBrief();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodaysBrief();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTodaysMarketPulseUpdate(): Promise<MarketPulseUpdate | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodaysMarketPulseUpdate();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodaysMarketPulseUpdate();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isProUser(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isProUser();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isProUser();
            return result;
        }
    }
    async listAlertRules(): Promise<Array<[bigint, AlertRule]>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAlertRules();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAlertRules();
            return result;
        }
    }
    async listDailyBriefs(): Promise<Array<[bigint, DailyBrief]>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDailyBriefs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDailyBriefs();
            return result;
        }
    }
    async listMarketPulseUpdates(): Promise<Array<[bigint, MarketPulseUpdate]>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMarketPulseUpdates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMarketPulseUpdates();
            return result;
        }
    }
    async listPortfolioSnapshots(): Promise<Array<PortfolioSnapshot>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPortfolioSnapshots();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPortfolioSnapshots();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async listResearchItems(): Promise<Array<[bigint, ResearchItem]>> {
        if (this.processError) {
            try {
                const result = await this.actor.listResearchItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listResearchItems();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveResearchItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveResearchItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveResearchItem(arg0);
            return result;
        }
    }
    async setProStatus(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setProStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setProStatus(arg0);
            return result;
        }
    }
    async toggleAlertRule(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleAlertRule(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleAlertRule(arg0);
            return result;
        }
    }
    async updateProfile(arg0: string, arg1: string, arg2: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_Asset_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Asset): Asset {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_PortfolioSnapshot_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PortfolioSnapshot): PortfolioSnapshot {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DailyBrief]): DailyBrief | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MarketPulseUpdate]): MarketPulseUpdate | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PortfolioSnapshot]): PortfolioSnapshot | null {
    return value.length === 0 ? null : from_candid_PortfolioSnapshot_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: bigint;
    assets: Array<_Asset>;
    opportunities: Array<string>;
    allocation: bigint;
    healthScore: bigint;
    risks: Array<string>;
}): {
    date: bigint;
    assets: Array<Asset>;
    opportunities: Array<string>;
    allocation: bigint;
    healthScore: bigint;
    risks: Array<string>;
} {
    return {
        date: value.date,
        assets: from_candid_vec_n12(_uploadFile, _downloadFile, value.assets),
        opportunities: value.opportunities,
        allocation: value.allocation,
        healthScore: value.healthScore,
        risks: value.risks
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    ticker: string;
    averageEntryPrice: [] | [bigint];
    name: string;
    timeHorizon: string;
    allocation: bigint;
}): {
    id: bigint;
    ticker: string;
    averageEntryPrice?: bigint;
    name: string;
    timeHorizon: string;
    allocation: bigint;
} {
    return {
        id: value.id,
        ticker: value.ticker,
        averageEntryPrice: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.averageEntryPrice)),
        name: value.name,
        timeHorizon: value.timeHorizon,
        allocation: value.allocation
    };
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Asset>): Array<Asset> {
    return value.map((x)=>from_candid_Asset_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PortfolioSnapshot>): Array<PortfolioSnapshot> {
    return value.map((x)=>from_candid_PortfolioSnapshot_n10(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
